### ISSUE TITLE
Time out after 60 seconds OpenQA.Selenium.WebDriverException

### ISSUE THREAD

**Issue by ashokkumarg** [Bumblebee/Bumblebee#95]
I get the following exception when navigating from one page to another page.

Result StackTrace:  
at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Firefox.FirefoxDriverCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteTargetLocator.DefaultContent()
   at Bumblebee.Implementation.Page.get_Tag()
   at Bumblebee.Implementation.WebPage.<get_Tag>b__0(IWebDriver driver)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at Bumblebee.Implementation.WebPage.get_Tag()
   at Bumblebee.Implementation.Block.FindElement(By by)
   at Bumblebee.Implementation.Block.get_Tag()
   at Bumblebee.Implementation.WebBlock.<get_Tag>b__0(IWebDriver driver)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at Bumblebee.Implementation.WebBlock.get_Tag()
   at Bumblebee.Implementation.Block.FindElement(By by)
   at Bumblebee.Implementation.Clickable`1..ctor(IBlock parent, By by)

   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
Result Message: 
OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:7055/hub/session/479032da-9432-47be-a73e-ba3e3942f102/frame timed out after 60 seconds.
  ----> System.Net.WebException : The operation has timed out

**Comment by toddmeinershagen** [comment]
Hi Ashok,

I am not familiar with using the RemoteDriver.

It appears that underneath the covers, it is using a WebRequest that is
timing out.  Are you able to navigate to any other pages within the
application?  Have you tried to navigate in a browser to the url that is
listed to see if it takes more than 60 seconds to open?


Todd

**Comment by ashokkumarg** [comment]
@toddmeinershagen When I enter the login credential and navigating to the home page i get this error.

**Comment by toddmeinershagen** [comment]
@ashokkumarg Not sure if you were able to get beyond this issue.  If not, let's talk some more.  Any code that can reproduce the issue consistently would help so that I can fix it locally, and if needed, apply changes to the code base.

**Comment by toddmeinershagen** [comment]
@ashokkumarg I haven't heard back about this issue, so I am not sure if it is still an issue for you.  I am going to close it for now.  Feel free to add a new issue and reference this one, if it is still occurring.
